#!/usr/bin/env bash
#Script that displays FizzBuzz in multiples of 3 and 5, fizz for multiple of 3 and buzz for multiple of 5
for i in $(seq 1 100); do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
