#!/usr/bin/env bash
#Displays specific contents of a file
while IFS=: read -r username password uid gid comment home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo ""
done < /etc/passwd
