#!/usr/bin/env bash
# Loops from 1 to 10, displaying bad luct at 4, good luck at 8 and Best school for the rest
i=0
while [ "$i" -lt 10 ]; do
	i=$((i + 1))
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
